server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ebook?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/ebook
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: w577159462@163.com
    password: FUYXEAIFAHCSTFRG
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp:
      auth: true

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
